# Generated by Django 4.0.2 on 2022-06-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaciones',
            name='apellido_mat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donaciones',
            name='apellido_pat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donaciones',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
