# Generated by Django 4.0.2 on 2022-06-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donaciones', '0002_alter_donaciones_apellido_mat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donaciones',
            name='fecha',
        ),
    ]
